# Numpy


In [1]:
# Básico empezar importando numpy
import numpy as np

# ndarray (n-dimensional array) es la estructura de datos principal en numpy
lista = [1, 2, 3, 4, 5]
array = np.array(lista)
# Consuta de atributos
print("Array:", array)
print("Tipo de dato:", type(array))
print("Dimensiones:", array.ndim)
print("Shape:", array.shape[0]) # Número de filas si quiero el número de columnas sería array.shape[1]
print("Tamaño:", array.size)

Array: [1 2 3 4 5]
Tipo de dato: <class 'numpy.ndarray'>
Dimensiones: 1
Shape: 5
Tamaño: 5


In [2]:
# Para crear arrays con valores iniciales específicos
mi_array = np.array([[1, 2, 3], [4, 5, 6]])
print("Array 2D:\n", mi_array)
mi_array_ceros = np.zeros((2, 3))  # Array de ceros de 2 filas y 3 columnas
print("Array de ceros:\n", mi_array_ceros)
mi_array_unos = np.ones((3, 2))   # Array de unos de 3 filas y 2 columnas
print("Array de unos:\n", mi_array_unos)
mi_array_vacio = np.empty((2, 4)) # Array vacío de 2 filas y 4 columnas
print("Array vacío:\n", mi_array_vacio)
mi_array_arange = np.arange(10, 20, 2) # Array con valores desde 10 hasta 20 con paso de 2
print("Array con arange:", mi_array_arange)

Array 2D:
 [[1 2 3]
 [4 5 6]]
Array de ceros:
 [[0. 0. 0.]
 [0. 0. 0.]]
Array de unos:
 [[1. 1.]
 [1. 1.]
 [1. 1.]]
Array vacío:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Array con arange: [10 12 14 16 18]


In [3]:
# Funciones para crear arrays 1 dimensión
mi_array = np.array([10, 20, 30, 40, 50])
a = np.ones_like(mi_array)  # Crea un array de unos con la misma forma que mi_array
print("Array de unos con la misma forma que mi_array:\n", a)
b = np.zeros_like(mi_array) # Crea un array de ceros con la misma forma que mi_array
print("Array de ceros con la misma forma que mi_array:\n", b)
c = np.empty_like(mi_array) # Crea un array vacío con la misma forma que mi_array
print("Array vacío con la misma forma que mi_array:\n", c)
d = np.full(mi_array.shape, 7) # Crea un array lleno con el valor 7 y la misma forma que mi_array
print("Array lleno con el valor 7:\n", d)
e = np.full_like(mi_array, 9) # Crea un array lleno con el valor 9 y la misma forma que mi_array
print("Array lleno con el valor 9:\n", e)
f = np.linspace(0, 1, 5) # Crea un array con 5 valores equiespaciados entre 0 y 1
print("Array con linspace:\n", f)

Array de unos con la misma forma que mi_array:
 [1 1 1 1 1]
Array de ceros con la misma forma que mi_array:
 [0 0 0 0 0]
Array vacío con la misma forma que mi_array:
 [            0 2302726373824 2302726375344 2302726375584             0]
Array lleno con el valor 7:
 [7 7 7 7 7]
Array lleno con el valor 9:
 [9 9 9 9 9]
Array con linspace:
 [0.   0.25 0.5  0.75 1.  ]


In [4]:
# Funciones estadísticas de Numpy de agrupamiento: Retornan 1 valor
data = np.array([2, 1, 5, 4, 3])
print(f"Array original: {data}")
media = np.mean(data)
mediana = np.median(data)
maximo = np.max(data)
minimo = np.min(data)
desviacion = np.std(data)
varianza = np.var(data)
suma = np.sum(data)
indice_max = np.argmax(data)
indice_min = np.argmin(data)
ordenar_menor_a_mayor = np.sort(data)
ordenados_sin_repetidos = np.unique(data)
print("Media:", media)
print("Mediana:", mediana)
print("Máximo:", maximo)
print("Mínimo:", minimo)
print("Desviación estándar:", desviacion)
print("Varianza:", varianza)
print("Suma:", suma)
print("Índice del máximo valor:", indice_max)
print("Índice del mínimo valor:", indice_min)
print("Array ordenado de menor a mayor:", ordenar_menor_a_mayor)
print("Array ordenado sin repetidos:", ordenados_sin_repetidos)

Array original: [2 1 5 4 3]
Media: 3.0
Mediana: 3.0
Máximo: 5
Mínimo: 1
Desviación estándar: 1.4142135623730951
Varianza: 2.0
Suma: 15
Índice del máximo valor: 2
Índice del mínimo valor: 1
Array ordenado de menor a mayor: [1 2 3 4 5]
Array ordenado sin repetidos: [1 2 3 4 5]


In [5]:
# En Numpy, los slice son "vistas" del array original y no copia de datos a nueva variable, cualquier
# modificación al slice afectará a los datos originales.
mi_array = np.arange(10)
print("Array original:", mi_array)
porcion = mi_array[2:7]
print("Porción del array (slice):", porcion)
porcion[0] = 99
print("Porción modificada:", porcion)
print("Array original después de modificar la porción:", mi_array)

# Se puede forzar una copia usando el método copy()
porcion_copia = mi_array[2:7].copy()
porcion_copia[0] = 55
print("\nPorción copia modificada:", porcion_copia)

Array original: [0 1 2 3 4 5 6 7 8 9]
Porción del array (slice): [2 3 4 5 6]
Porción modificada: [99  3  4  5  6]
Array original después de modificar la porción: [ 0  1 99  3  4  5  6  7  8  9]

Porción copia modificada: [55  3  4  5  6]


In [11]:
# Indexación booleana
mi_array = np.arange(5)
# Array de booleanos
array_bool = np.array([True, False, True, False, True])
# Indexación booleana, me devuelve los valores de mi_array que coinciden con True
array_indexado = mi_array[array_bool]
print("Array original:", mi_array)
print("Array booleano:", array_bool)
print("Array indexado con booleanos:", array_indexado)

# Ejemplo práctico de indexación booleana
nombres = np.array(['Ana', 'Luis', 'Maria', 'Juan', 'Pedro'])
sueldos = np.array([3000, 2500, 4000, 3500, 2800])
print(f"\nNombres con sueldos mayores a 3000€: {nombres[sueldos > 3000]}")  # Nombres con sueldos mayores a 3000

# Fancy Index: Indexar un array mediante una lista o ndarray de enteros. Esta lista de enteros indica los índices de los
# elementos que deseamos, en cualquier orden.
nombres = np.array(['Ana', 'Luis', 'Maria', 'Juan', 'Pedro'])
nombres_copia = nombres[[0, 2, 4]]  # Selecciona los elementos en las posiciones 0, 2 y 4
print("\nNombres seleccionados con fancy indexing:", nombres_copia)

Array original: [0 1 2 3 4]
Array booleano: [ True False  True False  True]
Array indexado con booleanos: [0 2 4]

Nombres con sueldos mayores a 3000€: ['Maria' 'Juan']

Nombres seleccionados con fancy indexing: ['Ana' 'Maria' 'Pedro']


In [14]:
# Unfunc de numpy: operaciones elemento a elemento
a = np.array([1, 2, 3, 4, 5])
print("Array original:", a)
valor_absoluto = np.abs(a)
print("Valor absoluto:", valor_absoluto)
raiz_cuadrada = np.sqrt(a)
print("Raíz cuadrada:", raiz_cuadrada)
cuadrado = np.square(a)
print("Cuadrado:", cuadrado)
redondear_entero_mas_cercano = np.rint(a)
print("Redondear al entero más cercano:", redondear_entero_mas_cercano)
signo = np.sign(a)
print("Signo:", signo)
modf = np.modf(a)
print("Parte decimal y parte entera:", modf)

Array original: [1 2 3 4 5]
Valor absoluto: [1 2 3 4 5]
Raíz cuadrada: [1.         1.41421356 1.73205081 2.         2.23606798]
Cuadrado: [ 1  4  9 16 25]
Redondear al entero más cercano: [1. 2. 3. 4. 5.]
Signo: [1 1 1 1 1]
Parte decimal y parte entera: (array([0., 0., 0., 0., 0.]), array([1., 2., 3., 4., 5.]))


In [15]:
# Unfunc binarias de numpy: operaciones entre dos arrays elemento a elemento
b = np.array([10, 20, 30, 40, 50])
suma = np.add(a, b)
valor_maximo = np.maximum(a, b)
valor_minimo = np.minimum(a, b)
print("Array a:", a)
print("Array b:", b)
print("Suma elemento a elemento:", suma)
print("Valor máximo elemento a elemento:", valor_maximo)
print("Valor mínimo elemento a elemento:", valor_minimo)

Array a: [1 2 3 4 5]
Array b: [10 20 30 40 50]
Suma elemento a elemento: [11 22 33 44 55]
Valor máximo elemento a elemento: [10 20 30 40 50]
Valor mínimo elemento a elemento: [1 2 3 4 5]


In [17]:
# Nan: Constante de numpy que representa "Not a Number" (No es un número)
print("Valor NaN de numpy:", np.nan)
# Comprobar si un valor es NaN
ar = np.array([1, 2, np.nan, 4])
print("Array:", ar)
print("Comprobar si los elementos son NaN:", np.isnan(ar))
print("Comprobar que sale en el elemento NaN:", np.isnan(ar[2]))



Valor NaN de numpy: nan
Array: [ 1.  2. nan  4.]
Comprobar si los elementos son NaN: [False False  True False]
Comprobar que sale en el elemento NaN: True


In [18]:
# Métodos para comprobar valores Booleanos
bool_array = np.array([True, False, True, True, False])
print("Algún True:", np.any(bool_array))
print("Todos son True:", np.all(bool_array))


Algún True: True
Todos son True: False


In [20]:
# Operaciones con conjuntos usando numpy
set1 = np.array([0, 1, 3, 5, 5, 2, 1, 7, 10, 12])
set2 = np.array([0, 2, 4, 6, 1, 2, 0, 8, 10, 12])

# Únicos
print("Elementos únicos en set1:", np.unique(set1))
print("Elementos únicos en set2:", np.unique(set2))
# Intersección
print("Intersección de set1 y set2:", np.intersect1d(set1, set2))
# Unión
print("Unión de set1 y set2:", np.union1d(set1, set2))
# In
print("Elementos de set1 que están en set2:", np.isin(set1, set2))
# Diferencia
print("Elementos en set1 que no están en set2:", np.setdiff1d(set1, set2))

Elementos únicos en set1: [ 0  1  2  3  5  7 10 12]
Elementos únicos en set2: [ 0  1  2  4  6  8 10 12]
Intersección de set1 y set2: [ 0  1  2 10 12]
Unión de set1 y set2: [ 0  1  2  3  4  5  6  7  8 10 12]
Elementos de set1 que están en set2: [ True  True False False False  True  True False  True  True]
Elementos en set1 que no están en set2: [3 5 7]


In [21]:
# Función Where: Devuelve los índices de los elementos que cumplen una condición
impares = np.array([1, 3, 5, 7, 9, 11, 13, 15])
pares = np.array([2, 4, 6, 8, 10, 12, 14, 16])
booleanos = np.array([True, False, True, False, True, False, True, False])
# Where.
resultado = np.where(booleanos, impares, pares)
print("Resultado de np.where:", resultado)
# También pueden ser escalares los array de datos
resultado = np.where(booleanos, impares, 0)
print("Resultado de np.where con escalar:", resultado)


Resultado de np.where: [ 1  4  5  8  9 12 13 16]
Resultado de np.where con escalar: [ 1  0  5  0  9  0 13  0]
