# Comparación Estructuras de control con NumPy

Esta tanda de ejercicios trata de comparar la potencia de numpy para hacer muchas cosas en pocas líneas de código. 

El **objetivo** es hacer 2 versiones de cada ejercicio:

+ Primero usando estructuras de control, es decir, hacer lo que se pide usando un bucle para recorrer el array, sin usar funciones o métodos de numpy (o lo menos posible).
+ Posteriormente, hacer otra versión usando toda la potencia de numpy.


El primer ejercicio se da hecho como ejemplo.


## Para realizar estos ejercicios hay que ver antes el tema 1 hasta el final.

# Datos

Partimos de 4 ndarray:

+ Notas de matemáticas (tipo entero)
+ Notas de físicas (tipo entero)
+ Nombres de alumnos.
+ Array adicional de números reales.

In [2]:
import numpy as np

notas_mates = np.random.randint(0, 11, 10)
notas_fisica = np.random.randint(0, 11, 10)
alumnos = np.array(["Juan", "Pedro", "Antonio", "Maria", "Pablo", "Carlos", "Lucia", "Marta", "Noelia", "Samuel"])
array_float = np.random.standard_normal(10)

print(notas_mates)
print(notas_fisica)
print(array_float)

[9 6 1 1 9 9 3 9 6 5]
[1 8 2 9 5 5 2 9 8 5]
[ 0.50489677  0.97810466  0.85119071 -1.00415311 -0.29737258 -1.36476029
 -0.6396545   1.17602755  0.02473524  1.70940911]


# 1. Obtener la suma de todas las notas de matemáticas 

Este se da hecho como ejemplo.

In [2]:
# Versión con estructuras de control
suma = 0
for elem in notas_mates:
    suma += elem
print(suma)

24


In [3]:
# Versión numpy
print(notas_mates.sum())

24


# Obtener la nota media de matemáticas

In [174]:
# Versión con estructuras de control
media = np.sum(notas_mates) / len(notas_mates)
print(media)

3.0


In [175]:
# Versión numpy
print(notas_mates.mean())

3.0


# Obtener un array con los nombres de los alumnos que han aprobado matemáticas

In [176]:
# Versión con estructuras de control
for i in range(len(notas_mates)):
    if notas_mates[i] >= 5:
        print(alumnos[i], end=" ")

Pedro Maria Carlos 

In [177]:
# Versión numpy
print(alumnos[notas_mates >= 5])

['Pedro' 'Maria' 'Carlos']


# Obtener un array con los nombres de aquellos alumnos con nota mayor a la nota media de mates

In [178]:
# Versión con estructuras de control
media = np.sum(notas_mates) / len(notas_mates)
print(media)
for i in range(len(notas_mates)):
    if notas_mates[i] >= media:
        print(f"El alumno {alumnos[i]} tiene una nota de {notas_mates[i]}")

3.0
El alumno Pedro tiene una nota de 8
El alumno Maria tiene una nota de 9
El alumno Carlos tiene una nota de 7
El alumno Samuel tiene una nota de 3


In [179]:
# Versión numpy
print(alumnos[notas_mates >= notas_mates.mean()])

['Pedro' 'Maria' 'Carlos' 'Samuel']


## Sumar 1 punto a aquellos alumnos que han suspendido mates (nota < 5)

In [180]:
# Versión con estructuras de control
for i in range(len(notas_mates)):
    if notas_mates[i] < 5:
        notas_mates[i] += 1
        print(f"El alumno {alumnos[i]} se le ha sumado 1 punto a su nota: {notas_mates[i]}")

El alumno Juan se le ha sumado 1 punto a su nota: 2
El alumno Antonio se le ha sumado 1 punto a su nota: 1
El alumno Pablo se le ha sumado 1 punto a su nota: 1
El alumno Lucia se le ha sumado 1 punto a su nota: 1
El alumno Marta se le ha sumado 1 punto a su nota: 3
El alumno Noelia se le ha sumado 1 punto a su nota: 1
El alumno Samuel se le ha sumado 1 punto a su nota: 4


In [181]:
# Versión numpy
print(f"El alumno {alumnos[notas_mates < 5]} se le ha sumado 1 punto en su nota: {notas_mates[notas_mates < 5] + 1}")

El alumno ['Juan' 'Antonio' 'Pablo' 'Lucia' 'Marta' 'Noelia' 'Samuel'] se le ha sumado 1 punto en su nota: [3 2 2 2 4 2 5]


## Sumar 2 punto a aquellos alumnos que han suspendido mates (nota < 5)
## Sumar 1 punto a los que han aprobado

In [182]:
# Versión con estructuras de control
for i in range(len(notas_mates)):
    if notas_mates[i] < 5:
        notas_mates[i] += 2
        print(f"El alumno {alumnos[i]} se le ha sumado 2 punto a su nota: {notas_mates[i]}")
    else:
        notas_mates[i] += 1
        print(f"El alumno {alumnos[i]} se le ha sumado 1 punto a su nota: {notas_mates[i]}")

El alumno Juan se le ha sumado 2 punto a su nota: 4
El alumno Pedro se le ha sumado 1 punto a su nota: 9
El alumno Antonio se le ha sumado 2 punto a su nota: 3
El alumno Maria se le ha sumado 1 punto a su nota: 10
El alumno Pablo se le ha sumado 2 punto a su nota: 3
El alumno Carlos se le ha sumado 1 punto a su nota: 8
El alumno Lucia se le ha sumado 2 punto a su nota: 3
El alumno Marta se le ha sumado 2 punto a su nota: 5
El alumno Noelia se le ha sumado 2 punto a su nota: 3
El alumno Samuel se le ha sumado 2 punto a su nota: 6


In [183]:
# Versión numpy
print(notas_mates)
condicion = notas_mates < 5
resultado = np.where(condicion, notas_mates + 2, notas_mates + 1)
print(resultado)

[ 4  9  3 10  3  8  3  5  3  6]
[ 6 10  5 11  5  9  5  6  5  7]


# Generar un ndarray a partir de array_float
# Si el número es negativo, convertirlo a positivo

In [5]:
# Versión con estructuras de control
lista = [10, -5, 3, 0, -2, 8, -1]
for elem in lista:
    if elem < 0:
        elem = +-elem
    print(elem)

10
5
3
0
2
8
1


In [6]:
# Versión numpy
array = np.array([10, -5, 3, 0, -2, 8, -1])
print(np.abs(array))

[10  5  3  0  2  8  1]


# Poner un 10  en mates al alumno Pedro

In [7]:
# Versión con estructuras de control
for i in range(len(notas_mates)):
    if alumnos[i] == "Pedro":
        notas_mates[i] = 10
        print(f"La nota de Pedro ha sido cambiada a {notas_mates[i]}")

La nota de Pedro ha sido cambiada a 10


In [8]:
# Versión numpy
notas_mates[alumnos == "Pedro"] = 10
print(f"La nota de Pedro ha sido cambiada a {notas_mates[alumnos == 'Pedro']}")

La nota de Pedro ha sido cambiada a [10]


# Elevar al cuadrado todas las notas de matemáticas

In [11]:
# Versión con estructuras de control
for i in range(len(notas_mates)):
    notas_mates[i] **2
print(notas_mates)

[ 81 100   1   1  81  81   9  81  36  25]


In [12]:
# Versión numpy
np.square(notas_mates)
print(notas_mates)

[ 81 100   1   1  81  81   9  81  36  25]


# Elevar al cuadrado las notas menores a 5 de matemáticas

In [13]:
# Versión con estructuras de control
for i in range(len(notas_mates)):
    if notas_mates[i] < 5:
        notas_mates[i] **2
        print(f"La nota de {alumnos[i]} ha sido cambiada a {notas_mates[i]}")

La nota de Antonio ha sido cambiada a 1
La nota de Maria ha sido cambiada a 1


In [15]:
# Versión numpy
mayor = np.where(notas_mates < 5, notas_mates**2, notas_mates)
print(mayor)

[ 81 100   1   1  81  81   9  81  36  25]


# Generar un ndarray que guarde el signo del array array_float. 

El signo se marca con lo siguiente:
+ -1 Si el signo es negativo
+ 0 si el número es 0
+ 1 si el signo es positivo

In [16]:
# Versión con estructuras de control
positivos = 1
negativos = -1
ceros = 0
for i in range(len(notas_mates)):
    if notas_mates[i] > 0:
        notas_mates[i] = positivos
    elif notas_mates[i] < 0:
        notas_mates[i] = negativos
    else:
        notas_mates[i] = ceros
print(notas_mates)

[1 1 1 1 1 1 1 1 1 1]


In [17]:
# Versión numpy
negativos = np.where(notas_mates < 0, -1, notas_mates)
ceros = np.where(negativos == 0, 0, negativos)
positivos = np.where(ceros > 0, 1, ceros)
print(positivos)

[1 1 1 1 1 1 1 1 1 1]


# Generar un ndarray que guarde la nota mínima de cada alumno entre mates y física

In [ ]:
# Versión con estructuras de control
nota_minima = 11
for i in range(len(notas_mates)):
    if notas_mates[i] < notas_fisica[i]:
        nota_minima = notas_mates[i]
    else:
        nota_minima = notas_fisica[i]
    print(f"La nota mínima de {alumnos[i]} es {nota_minima}")


La nota mínima de Juan es 1
La nota mínima de Pedro es 1
La nota mínima de Antonio es 1
La nota mínima de Maria es 1
La nota mínima de Pablo es 1
La nota mínima de Carlos es 1
La nota mínima de Lucia es 1
La nota mínima de Marta es 1
La nota mínima de Noelia es 1
La nota mínima de Samuel es 1


In [ ]:
# Versión numpy
minimas = np.minimum(notas_mates, notas_fisica)
for i in range(len(alumnos)):
    print(f"La nota mínima de {alumnos[i]} es {minimas[i]}")

La nota mínima de Juan es 1
La nota mínima de Pedro es 1
La nota mínima de Antonio es 1
La nota mínima de Maria es 1
La nota mínima de Pablo es 1
La nota mínima de Carlos es 1
La nota mínima de Lucia es 1
La nota mínima de Marta es 1
La nota mínima de Noelia es 1
La nota mínima de Samuel es 1


# Comprobar si alguien tiene un 10 matemáticas

In [20]:
# Versión con estructuras de control
tiene_diez = False
for i in range(len(notas_mates)):
    if notas_mates[i] == 10:
        tiene_diez = True
        print(f"El alumno {alumnos[i]} tiene un 10 en matemáticas.")
if not tiene_diez:
    print("Ningún alumno tiene un 10 en matemáticas.")

Ningún alumno tiene un 10 en matemáticas.


In [ ]:
# Versión numpy
if np.any(notas_mates == 10):
    alumnos_con_diez = alumnos[notas_mates == 10]
    for alumno in alumnos_con_diez:
        print(f"El alumno {alumno} tiene un 10 en matemáticas.")
else:
    print("Ningún alumno tiene un 10 en matemáticas.")

Ningún alumno tiene un 10 en matemáticas.


# Comprobar si todos han aprobado física

In [27]:
# Versión con estructuras de control
todos_aprobados = True
for i in range(len(notas_fisica)):
    if notas_fisica[i] < 5:
        todos_aprobados = False
        print(f"El alumno {alumnos[i]} no ha aprobado física.")
if todos_aprobados:
    print("Todos los alumnos han aprobado física.")

El alumno Juan no ha aprobado física.
El alumno Antonio no ha aprobado física.
El alumno Lucia no ha aprobado física.


In [26]:
# Versión numpy
if np.all(notas_fisica >= 5):
    print("Todos los alumnos han aprobado física.")
else:
    alumnos_no_aprobados = alumnos[notas_fisica < 5]
    for alumno in alumnos_no_aprobados:
        print(f"El alumno {alumno} no ha aprobado física.")

El alumno Juan no ha aprobado física.
El alumno Antonio no ha aprobado física.
El alumno Lucia no ha aprobado física.


# Generar un array de nombres de quienes han aprobado mates y física

In [25]:
# Versión con estructuras de control
aprobados = []
for i in range(len(notas_mates)):
    if notas_mates[i] >= 5 and notas_fisica[i] >= 5:
        aprobados.append(alumnos[i])
print("Alumnos que han aprobado ambas materias:", aprobados)

Alumnos que han aprobado ambas materias: []


In [24]:
# Versión numpy
# Generar un array de nombres de quienes han aprobado mates y física
aprobados = alumnos[(notas_mates >= 5) & (notas_fisica >= 5)]
print("Alumnos que han aprobado ambas materias:", aprobados)

Alumnos que han aprobado ambas materias: []


# Generar un array de nombres de quien ha aprobado mates pero no física

In [23]:
# Versión con estructuras de control
# Generar un array de nombres de quien ha aprobado mates pero no física
aprobados_mates_no_fisica = []
for i in range(len(notas_mates)):
    if notas_mates[i] >= 5 and notas_fisica[i] < 5:
        aprobados_mates_no_fisica.append(alumnos[i])
print("Alumnos que han aprobado mates pero no física:", aprobados_mates_no_fisica) 

Alumnos que han aprobado mates pero no física: []


In [22]:
# Versión numpy
# Generar un array de nombres de quien ha aprobado mates pero no física
aprobados_mates_no_fisica = alumnos[(notas_mates >= 5) & (notas_fisica < 5)]
print("Alumnos que han aprobado mates pero no física:", aprobados_mates_no_fisica)

Alumnos que han aprobado mates pero no física: []
