# Comparación Estructuras de control con NumPy

Esta tanda de ejercicios trata de comparar la potencia de numpy para hacer muchas cosas en pocas líneas de código. 

El **objetivo** es hacer 2 versiones de cada ejercicio:

+ Primero usando estructuras de control, es decir, hacer lo que se pide usando un bucle para recorrer el array, sin usar funciones o métodos de numpy (o lo menos posible).
+ Posteriormente, hacer otra versión usando toda la potencia de numpy.


El primer ejercicio se da hecho como ejemplo.


## Para realizar estos ejercicios hay que ver antes el tema 1 hasta el final.

# Datos

Partimos de 4 ndarray:

+ Notas de matemáticas (tipo entero)
+ Notas de físicas (tipo entero)
+ Nombres de alumnos.
+ Array adicional de números reales.

In [1]:
import numpy as np

notas_mates = np.random.randint(0, 11, 10)
notas_fisica = np.random.randint(0, 11, 10)
alumnos = np.array(["Juan", "Pedro", "Antonio", "Maria", "Pablo", "Carlos", "Lucia", "Marta", "Noelia", "Samuel"])
array_float = np.random.standard_normal(10)

print(notas_mates)
print(notas_fisica)
print(array_float)

[1 6 4 2 2 1 4 4 0 0]
[0 2 2 9 2 6 1 4 6 1]
[ 0.71055418  0.79700161 -0.14935944  0.67573938 -0.74114103 -1.1220145
 -1.04713225 -0.43831306 -0.75289735  0.59588733]


# 1. Obtener la suma de todas las notas de matemáticas 

Este se da hecho como ejemplo.

In [2]:
# Versión con estructuras de control
suma = 0
for elem in notas_mates:
    suma += elem
print(suma)

24


In [3]:
# Versión numpy
print(notas_mates.sum())

24


# Obtener la nota media de matemáticas

In [174]:
# Versión con estructuras de control
media = np.sum(notas_mates) / len(notas_mates)
print(media)

3.0


In [175]:
# Versión numpy
print(notas_mates.mean())

3.0


# Obtener un array con los nombres de los alumnos que han aprobado matemáticas

In [176]:
# Versión con estructuras de control
for i in range(len(notas_mates)):
    if notas_mates[i] >= 5:
        print(alumnos[i], end=" ")

Pedro Maria Carlos 

In [177]:
# Versión numpy
print(alumnos[notas_mates >= 5])

['Pedro' 'Maria' 'Carlos']


# Obtener un array con los nombres de aquellos alumnos con nota mayor a la nota media de mates

In [178]:
# Versión con estructuras de control
media = np.sum(notas_mates) / len(notas_mates)
print(media)
for i in range(len(notas_mates)):
    if notas_mates[i] >= media:
        print(f"El alumno {alumnos[i]} tiene una nota de {notas_mates[i]}")

3.0
El alumno Pedro tiene una nota de 8
El alumno Maria tiene una nota de 9
El alumno Carlos tiene una nota de 7
El alumno Samuel tiene una nota de 3


In [179]:
# Versión numpy
print(alumnos[notas_mates >= notas_mates.mean()])

['Pedro' 'Maria' 'Carlos' 'Samuel']


## Sumar 1 punto a aquellos alumnos que han suspendido mates (nota < 5)

In [180]:
# Versión con estructuras de control
for i in range(len(notas_mates)):
    if notas_mates[i] < 5:
        notas_mates[i] += 1
        print(f"El alumno {alumnos[i]} se le ha sumado 1 punto a su nota: {notas_mates[i]}")

El alumno Juan se le ha sumado 1 punto a su nota: 2
El alumno Antonio se le ha sumado 1 punto a su nota: 1
El alumno Pablo se le ha sumado 1 punto a su nota: 1
El alumno Lucia se le ha sumado 1 punto a su nota: 1
El alumno Marta se le ha sumado 1 punto a su nota: 3
El alumno Noelia se le ha sumado 1 punto a su nota: 1
El alumno Samuel se le ha sumado 1 punto a su nota: 4


In [181]:
# Versión numpy
print(f"El alumno {alumnos[notas_mates < 5]} se le ha sumado 1 punto en su nota: {notas_mates[notas_mates < 5] + 1}")

El alumno ['Juan' 'Antonio' 'Pablo' 'Lucia' 'Marta' 'Noelia' 'Samuel'] se le ha sumado 1 punto en su nota: [3 2 2 2 4 2 5]


## Sumar 2 punto a aquellos alumnos que han suspendido mates (nota < 5)
## Sumar 1 punto a los que han aprobado

In [182]:
# Versión con estructuras de control
for i in range(len(notas_mates)):
    if notas_mates[i] < 5:
        notas_mates[i] += 2
        print(f"El alumno {alumnos[i]} se le ha sumado 2 punto a su nota: {notas_mates[i]}")
    else:
        notas_mates[i] += 1
        print(f"El alumno {alumnos[i]} se le ha sumado 1 punto a su nota: {notas_mates[i]}")

El alumno Juan se le ha sumado 2 punto a su nota: 4
El alumno Pedro se le ha sumado 1 punto a su nota: 9
El alumno Antonio se le ha sumado 2 punto a su nota: 3
El alumno Maria se le ha sumado 1 punto a su nota: 10
El alumno Pablo se le ha sumado 2 punto a su nota: 3
El alumno Carlos se le ha sumado 1 punto a su nota: 8
El alumno Lucia se le ha sumado 2 punto a su nota: 3
El alumno Marta se le ha sumado 2 punto a su nota: 5
El alumno Noelia se le ha sumado 2 punto a su nota: 3
El alumno Samuel se le ha sumado 2 punto a su nota: 6


In [183]:
# Versión numpy
print(notas_mates)
condicion = notas_mates < 5
resultado = np.where(condicion, notas_mates + 2, notas_mates + 1)
print(resultado)

[ 4  9  3 10  3  8  3  5  3  6]
[ 6 10  5 11  5  9  5  6  5  7]


# Generar un ndarray a partir de array_float
# Si el número es negativo, convertirlo a positivo

In [ ]:
# Versión con estructuras de control


SyntaxError: incomplete input (170186082.py, line 5)

In [ ]:
# Versión numpy

# Poner un 10  en mates al alumno Pedro

In [ ]:
# Versión con estructuras de control

In [ ]:
# Versión numpy

# Elevar al cuadrado todas las notas de matemáticas

In [ ]:
# Versión con estructuras de control

In [ ]:
# Versión numpy

# Elevar al cuadrado las notas menores a 5 de matemáticas

In [ ]:
# Versión con estructuras de control

In [ ]:
# Versión numpy

# Generar un ndarray que guarde el signo del array array_float. 

El signo se marca con lo siguiente:
+ -1 Si el signo es negativo
+ 0 si el número es 0
+ 1 si el signo es positivo

In [ ]:
# Versión con estructuras de control

In [ ]:
# Versión numpy

# Generar un ndarray que guarde la nota mínima de cada alumno entre mates y física

In [ ]:
# Versión con estructuras de control

In [ ]:
# Versión numpy

# Comprobar si alguien tiene un 10 matemáticas

In [ ]:
# Versión con estructuras de control

In [ ]:
# Versión numpy

# Comprobar si todos han aprobado física

In [ ]:
# Versión con estructuras de control

In [ ]:
# Versión numpy

# Generar un array de nombres de quienes han aprobado mates y física

In [ ]:
# Versión con estructuras de control

In [ ]:
# Versión numpy

# Generar un array de nombres de quien ha aprobado mates pero no física

In [ ]:
# Versión con estructuras de control

In [ ]:
# Versión numpy