# Array de datos inicial

Disponemos de 2 arrays de datos:

+ ndarray de nombres
+ ndarray de notas

Los arrays tienen el mismo tamaño y se relacionan por su índice. "Alberto" ocupta el índice 0, su nota corresponde al índice 0.


Para hacer estos ejercicios hay que avanzar en el **Tema 1 hasta la página 24**

Estos ejercicios se realizan invocando funcionalidades de numpy, por lo que cada acción que se pide se realiza en una o dos líneas de código, sin utilizar estructuras de control

In [69]:
import numpy as np

nombres = np.array(["Alberto", "Álvaro", "Antonio", "Guillermo", "José Manuel", "Juan Diego", "Juan Ignacio",
                    "Juan José", "María", "Raúl", "Victor"])
print(nombres)
notas = np.random.randint(1, 11, nombres.size)
print(notas)

['Alberto' 'Álvaro' 'Antonio' 'Guillermo' 'José Manuel' 'Juan Diego'
 'Juan Ignacio' 'Juan José' 'María' 'Raúl' 'Victor']
[ 8  8  8 10  1  5  4 10  5  2  5]


# Métodos del ndarray, funciones de numpy y slicing

Realiza lo que se pide en cada comentario usando un método del propio objeto ndarray, función directa de numpy o el slice igual que en listas.



In [70]:
import numpy as np
# Muestra Nota media de los alumnos
media = np.sum(notas) / len(notas)
print(f"La media es de {media}")
# Muestra Desviación estándar
print(f"Desviación estándar: {np.std(notas)}")

# Mostrar nombres del revés mediante una slice
print(f"Nombres ordenados al revés\n{nombres[-1::-1]}")

# Ordenar, haciendo una copia de datos en otra variable, las notas de menor a mayor
copy_notas = notas.copy()
copy_notas.sort()
print(copy_notas)

La media es de 6.0
Desviación estándar: 2.891995221924885
Nombres ordenados al revés
['Victor' 'Raúl' 'María' 'Juan José' 'Juan Ignacio' 'Juan Diego'
 'José Manuel' 'Guillermo' 'Antonio' 'Álvaro' 'Alberto']
[ 1  2  4  5  5  5  8  8  8 10 10]


# Aritmética, Comparaciones e indexación booleana

Estos ejercicios requieren alguna comparación de arrays, indexación booleana y aritmética, además de alguna función o método de numpy. Si no controlas la indexación booleana busca antes en los apuntes y realiza tus propias pruebas hasta controlar cómo funcionan.

In [71]:
# Sumar 1 a todas las notas
notas += 1
print(notas)

# Muestra cuántos hay aprobados
print((notas >= 5).sum())
# aprobados = 0
# for i in notas:
#     if i >= 5:
#         aprobados += 1
# print(f"Han aprobado {aprobados} alumnos.")

# Mostrar nombres de alumnos aprobados
print(nombres[notas > 5])

# Mostrar nombres con nota superior a la media
media = np.sum(notas) / len(notas)
print(nombres[notas > media])

# Asignar un 5 a los que tienen un 4
notas[notas == 4] = 5
print(notas)

# Sumar 1 a todas las notas mayores a 4
notas[notas > 4] += 1
print(notas)

[ 9  9  9 11  2  6  5 11  6  3  6]
9
['Alberto' 'Álvaro' 'Antonio' 'Guillermo' 'Juan Diego' 'Juan José' 'María'
 'Victor']
['Alberto' 'Álvaro' 'Antonio' 'Guillermo' 'Juan José']
[ 9  9  9 11  2  6  5 11  6  3  6]
[10 10 10 12  2  7  6 12  7  3  7]
